; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ZasLauncher"
#define MyAppVersion "1.0.0.15"
#define MyAppPublisher "ZAS Group s.r.o."
#define MyAppURL "https://www.zasgroup.cz"
#define MyAppExeName "ZasLauncher.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".zstg"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7A88E4FF-B59B-442D-A6F0-9993D59CD1F7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=y:\ZASproducts\ZAS.SimpleTestGUI.Core\publish
OutputBaseFilename=ZasLauncher.Install
SetupIconFile=y:\ZASproducts\ZAS.SimpleTestGUI.Core\ZAS.SimpleTestGUI.Core\Assets\zasgroup.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "y:\ZASproducts\ZAS.SimpleTestGUI.Core\publish\publish-win\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "y:\ZASproducts\ZAS.SimpleTestGUI.Core\publish\publish-win\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "y:\ZASproducts\ZAS.SimpleTestGUI.Core\publish\publish-win\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "y:\ZASproducts\ZAS.SimpleTestGUI.Core\publish\publish-win\libonigwrap.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "y:\ZASproducts\ZAS.SimpleTestGUI.Core\publish\publish-win\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

